[tool.pyright]
include = ["backend"]
exclude = [
    "**/node_modules",
    "**/__pycache__",
    "**/venv",
    "**/.venv"
]
venvPath = "."
venv = "backend/venv"
pythonVersion = "3.12"
typeCheckingMode = "basic"
reportMissingImports = true
reportMissingTypeStubs = false

[tool.pylsp]
plugins = {
    pylint = { enabled = false },
    pyflakes = { enabled = false },
    pycodestyle = { enabled = false }
}

